name: Monitor Alpinestars
on:
  schedule:
    - cron: '0 9,15,21 * * *' # Se ejecuta 3 veces al día
  workflow_dispatch: # Botón para prueba manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests beautifulsoup4
      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alpinestars.py
