name: Monitor de Precios y Stock
on:
  schedule:
    - cron: '0 9,15,21 * * *' # Se ejecuta a las 10:00, 16:00 y 22:00 (hora España)
  workflow_dispatch: # Permite ejecución manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests beautifulsoup4
      - name: Ejecutar scripts
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python alpinestars.py
          python zapatillas.py
